const std = @import("std");
const types = @import("types.zig");
const packet = @import("packet.zig");
const frame = @import("frame.zig");
const connection = @import("connection.zig");
pub const connection_pool = @import("connection_pool.zig");
const stream = @import("stream.zig");
const recovery = @import("recovery.zig");
const congestion = @import("congestion.zig");
const crypto = @import("crypto.zig");
const http3 = @import("../protocol/http3.zig");
const metrics_mw = @import("../middleware/metrics_mw.zig");
const build_options = @import("build_options");
const test_utils = @import("test_utils.zig");
const tls = @import("../tls/provider.zig");

/// QUIC packet handler
///
/// Processes incoming QUIC datagrams and produces responses.

pub const Error = error{
    InvalidPacket,
    ConnectionNotFound,
    HandshakeFailed,
    ProtocolError,
    OutOfMemory,
    DecryptionFailed,
};

/// Result of processing a packet
pub const ProcessResult = struct {
    /// Response data to send (if any)
    response: ?[]const u8 = null,
    /// Connection that handled the packet
    conn: ?*connection.Connection = null,
    /// New connection was created
    new_connection: bool = false,
    /// Connection should be closed
    close_connection: bool = false,
    /// HTTP/3 events generated (headers received, data received, etc.)
    http3_events: []http3.Event = &.{},
};

/// Server-wide QUIC metrics
pub const metrics = @import("metrics.zig");

/// QUIC Handler for processing packets
pub const Handler = struct {
    allocator: std.mem.Allocator,
    pool: connection_pool.ConnectionPool,
    /// Buffer for building outgoing UDP datagrams. Sized to fit a coalesced
    /// Initial + Handshake flight with a typical TLS 1.3 cert chain
    /// (ServerHello ~120B, EE+Cert+CertVerify+Finished ~2-3 KiB).
    response_buffer: [16 * 1024]u8 = undefined,
    /// Is this a server handler?
    is_server: bool,
    /// Server-wide metrics
    server_metrics: metrics.ServerMetrics = .{},
    /// TLS provider used to bootstrap a TLS session for each new QUIC
    /// connection (server: handshake processing, key derivation). Null
    /// when TLS is disabled at build time or no cert was configured.
    tls_provider: ?*tls.Provider = null,

    pub fn init(allocator: std.mem.Allocator, is_server: bool, max_connections: usize) Handler {
        return .{
            .allocator = allocator,
            .pool = connection_pool.ConnectionPool.init(allocator, is_server, max_connections),
            .is_server = is_server,
        };
    }

    /// Wire a TLS provider into the handler. Must be called before the
    /// first incoming Initial packet for h3 to work — otherwise
    /// connection.tls_session stays null and no TLS handshake runs.
    pub fn setTlsProvider(self: *Handler, provider: *tls.Provider) void {
        self.tls_provider = provider;
    }

    /// Get server-wide metrics
    pub fn getMetrics(self: *const Handler) *const metrics.ServerMetrics {
        return &self.server_metrics;
    }

    pub fn deinit(self: *Handler) void {
        self.pool.deinit();
    }

    /// Process an incoming QUIC datagram
    pub fn processPacket(
        self: *Handler,
        data: []const u8,
        peer_addr: connection_pool.SockAddrStorage,
    ) Error!ProcessResult {
        var result = ProcessResult{};

        // Parse packet header
        const parse_result = packet.parseHeader(data, 8); // Assume 8-byte CIDs
        if (parse_result.state != .complete) {
            return Error.InvalidPacket;
        }

        const header = parse_result.header orelse return Error.InvalidPacket;

        // Find or create connection
        var conn: *connection.Connection = undefined;
        // Note: we'll clear pending h3 events on the connection as soon as
        // we have one in hand (after the long/short header dispatch below).
        // This avoids returning stale events from a previous packet when
        // the current packet is a duplicate that processStreamFrame
        // early-returns on.

        // Helper: reset per-packet h3 scratch state on the connection
        // so this packet only ever sees events and header storage
        // generated by its own frames. Clears the events list AND the
        // Stack's per-packet `header_count` cursor — the latter is
        // where `copyHeaders` packs decoded request headers, and it
        // must reset between packets so the next packet's parsing
        // starts at offset 0 without clobbering any live slice held
        // by the previous packet's now-dispatched events.
        const clearEvents = struct {
            fn call(c: *connection.Connection) void {
                if (c.http3_stack) |*stack| {
                    stack.events.clearRetainingCapacity();
                    stack.resetPerPacketScratch();
                }
            }
        }.call;

        switch (header) {
            .long => |long| {
                // Try to find by DCID first
                if (self.pool.findByCid(long.dcid)) |c| {
                    conn = c;
                } else if (long.packet_type == .initial and self.is_server) {
                    // Create new connection for Initial packet
                    conn = self.pool.createConnection(long.dcid, peer_addr) catch |err| {
                        return switch (err) {
                            connection_pool.Error.OutOfMemory => Error.OutOfMemory,
                            else => Error.ConnectionNotFound,
                        };
                    };
                    // Bootstrap the TLS session so the QUIC TLS handshake
                    // can produce a server flight. Without this the
                    // connection would have no tls_session and TLS would
                    // never run, so the server would only ever ack.
                    if (self.tls_provider) |provider| {
                        conn.initTls(provider) catch |err| {
                            std.log.warn("h3: initTls failed: {}", .{err});
                            return Error.HandshakeFailed;
                        };
                    }
                    result.new_connection = true;
                    // Record new QUIC connection attempt
                    metrics_mw.getStore().recordQuicConnectionAttempt();
                } else {
                    return Error.ConnectionNotFound;
                }

                clearEvents(conn);
                // Process based on packet type
                switch (long.packet_type) {
                    .initial => {
                        try self.handleInitialPacket(conn, long, data);
                    },
                    .handshake => {
                        try self.handleHandshakePacket(conn, long, data);
                    },
                    .zero_rtt => {
                        // 0-RTT early data
                        if (conn.crypto_ctx.canAcceptEarlyData()) {
                            try self.handleZeroRttPacket(conn, long, data);
                            result.http3_events = getHttp3Events(conn);
                        }
                        // If early data not accepted, packet is silently dropped
                    },
                    .retry => {
                        // Retry handling (client-side)
                    },
                }
                // Build whatever needs to go on the wire after handling
                // this long-header packet (could be Initial+Handshake
                // flight, Handshake-only, or 1-RTT once handshake is done).
                result.response = try self.buildResponseFlight(conn);
            },
            .short => |short| {
                // Find connection by DCID
                conn = self.pool.findByCid(short.dcid) orelse {
                    return Error.ConnectionNotFound;
                };

                clearEvents(conn);
                try self.handleShortPacket(conn, short, data);

                // Collect HTTP/3 events after processing
                result.http3_events = getHttp3Events(conn);

                // Build outgoing 1-RTT response (ACK + HANDSHAKE_DONE +
                // any HTTP/3 stream data the application produced).
                result.response = try self.buildResponseFlight(conn);
            },
        }

        result.conn = conn;
        result.close_connection = !conn.isAlive();

        // Record packet received
        metrics_mw.getStore().recordQuicPackets(0, 1, 0);

        return result;
    }

    fn handleInitialPacket(
        self: *Handler,
        conn: *connection.Connection,
        header: packet.LongHeader,
        data: []const u8,
    ) Error!void {
        _ = self;

        // Update peer's connection ID
        if (header.scid.len > 0) {
            conn.peer_cid = header.scid;
        }

        // Get Initial keys for decryption
        const keys_opt: ?crypto.Keys = if (conn.is_server)
            conn.crypto_ctx.initial.client // Decrypt with client's key
        else
            conn.crypto_ctx.initial.server; // Decrypt with server's key
        const keys = keys_opt orelse return Error.HandshakeFailed;

        // Decrypt and process Initial packet
        try processEncryptedPacket(conn, &keys, header, data, types.PacketNumberSpace.initial);

        // Transition state
        if (conn.state == .initial) {
            conn.state = .handshaking;
        }

        // Advance TLS handshake if session exists
        if (conn.tls_session != null) {
            const handshake_complete = conn.advanceTlsHandshake() catch false;
            if (handshake_complete) {
                conn.onHandshakeComplete();
                // Record handshake completion in global metrics
                metrics_mw.getStore().recordQuicHandshakeComplete(conn.conn_metrics.handshakeLatencyMs());
            }
        }
    }

    fn handleHandshakePacket(
        self: *Handler,
        conn: *connection.Connection,
        header: packet.LongHeader,
        data: []const u8,
    ) Error!void {
        _ = self;

        // Get Handshake keys for decryption
        const keys_opt: ?crypto.Keys = if (conn.is_server)
            conn.crypto_ctx.handshake.client
        else
            conn.crypto_ctx.handshake.server;
        const keys = keys_opt orelse {
            // No handshake keys yet — expected very early in handshake
            return Error.HandshakeFailed;
        };

        // Decrypt and process Handshake packet
        try processEncryptedPacket(conn, &keys, header, data, types.PacketNumberSpace.handshake);

        // Advance TLS handshake
        if (conn.tls_session != null) {
            const handshake_complete = conn.advanceTlsHandshake() catch false;
            if (handshake_complete and conn.state == .handshaking) {
                conn.onHandshakeComplete();
                // Record handshake completion in global metrics
                metrics_mw.getStore().recordQuicHandshakeComplete(conn.conn_metrics.handshakeLatencyMs());
            }
        }
    }

    /// Handle 0-RTT packet (early data)
    fn handleZeroRttPacket(
        self: *Handler,
        conn: *connection.Connection,
        header: packet.LongHeader,
        data: []const u8,
    ) Error!void {
        _ = self;

        // 0-RTT packets are only sent by clients, so server decrypts with client key
        const keys = conn.crypto_ctx.early_data.client orelse {
            return Error.DecryptionFailed;
        };

        // Decrypt and process 0-RTT packet
        // 0-RTT uses the same packet number space as application data
        try processEncryptedPacket(conn, &keys, header, data, types.PacketNumberSpace.application);

        // Mark that we've accepted early data
        conn.early_data_received = true;
    }

    /// Process an encrypted long header packet (Initial or Handshake)
    fn processEncryptedPacket(
        conn: *connection.Connection,
        keys: *const crypto.Keys,
        header: packet.LongHeader,
        data: []const u8,
        pn_space: types.PacketNumberSpace,
    ) Error!void {
        const pn_offset = header.packet_number_offset;
        // RFC 9000 §17.2: Length field covers (Packet Number + Payload).
        // The full Initial/Handshake packet ends at pn_offset + payload_length.
        // Any bytes beyond are coalesced packets or trailing data, NOT part of
        // this packet's AEAD-protected ciphertext.
        const packet_len = pn_offset + header.payload_length;
        if (packet_len > data.len) return Error.InvalidPacket;

        // Copy packet to mutable buffer for decryption
        var decrypt_buf: [65536]u8 = undefined;
        if (packet_len > decrypt_buf.len) return Error.InvalidPacket;
        @memcpy(decrypt_buf[0..packet_len], data[0..packet_len]);

        // Get largest PN for this space
        const space = conn.getPacketSpace(pn_space);
        const largest_pn = space.largest_received orelse 0;

        // Unprotect the packet
        const unprotect_result = crypto.unprotectPacket(
            keys,
            largest_pn,
            pn_offset,
            &decrypt_buf,
            packet_len,
        ) catch return Error.InvalidPacket;

        // Dedupe: if we've already processed this packet number, just
        // mark it as received again (so the ACK still goes out) and
        // return. Reprocessing a duplicate would re-emit application
        // events and trigger duplicate responses on h3 streams.
        if (space.isDuplicate(unprotect_result.pn)) {
            space.ack_needed = true;
            return;
        }

        // Record packet received
        space.onPacketReceived(unprotect_result.pn);

        // Parse and process frames from decrypted payload
        const payload = decrypt_buf[unprotect_result.header_len .. unprotect_result.header_len + unprotect_result.payload_len];
        try processCryptoFrames(conn, payload, pn_space);
    }

    /// Process CRYPTO frames from Initial/Handshake packets.
    ///
    /// CRYPTO frames within a packet may arrive out of offset order
    /// (curl/ngtcp2 deliberately fragments and reorders for interop testing).
    /// We feed them through the connection's per-level reassembly buffer,
    /// which only emits contiguous prefixes to TLS — that lets OpenSSL parse
    /// the handshake messages correctly.
    fn processCryptoFrames(conn: *connection.Connection, payload: []const u8, space: types.PacketNumberSpace) Error!void {
        var offset: usize = 0;

        while (offset < payload.len) {
            const result = frame.parseFrame(payload[offset..]) catch return Error.InvalidPacket;
            offset += result.consumed;

            switch (result.frame) {
                .padding => {}, // Ignore padding
                .ping => {}, // PING just triggers ACK
                .ack => |ack| {
                    conn.processAckFrame(ack, space);
                },
                .crypto => |crypto_frame| {
                    // Hand the (offset, bytes) tuple to the connection's
                    // per-level reassembly buffer; it will feed any new
                    // contiguous prefix to TLS via feedCryptoData.
                    conn.ingestCryptoFrame(space, crypto_frame.offset, crypto_frame.data) catch |err| {
                        std.log.debug("QUIC crypto reassembly failed: {}", .{err});
                    };
                },
                else => {}, // Ignore other frame types in Initial/Handshake
            }
        }
    }

    fn handleShortPacket(
        self: *Handler,
        conn: *connection.Connection,
        header: packet.ShortHeader,
        data: []const u8,
    ) Error!void {
        _ = self;

        // Connection must be in connected state — clients can race their
        // 1-RTT data ahead of our handshake completion. Drop silently so
        // they retransmit; we'll process it once handshake_complete fires.
        if (conn.state != .connected) {
            return;
        }

        // Get application keys for decryption
        const keys_opt: ?crypto.Keys = if (conn.is_server)
            conn.crypto_ctx.application.client // Decrypt with client's key
        else
            conn.crypto_ctx.application.server; // Decrypt with server's key
        const keys = keys_opt orelse return Error.HandshakeFailed;

        // Calculate packet number offset
        // Short header: flags (1) + DCID (variable)
        const pn_offset = 1 + header.dcid.len;

        // Copy packet to mutable buffer for decryption
        var decrypt_buf: [65536]u8 = undefined;
        if (data.len > decrypt_buf.len) return Error.InvalidPacket;
        @memcpy(decrypt_buf[0..data.len], data);

        // Unprotect the packet (removes header protection and decrypts)
        const largest_pn = conn.application_space.largest_received orelse 0;
        const unprotect_result = crypto.unprotectPacket(
            &keys,
            largest_pn,
            pn_offset,
            &decrypt_buf,
            data.len,
        ) catch return Error.InvalidPacket;

        // Dedupe: drop duplicates after marking ack_needed so the
        // retransmit still gets ACKed but doesn't fire HTTP/3 events
        // for a stream we already responded to.
        if (conn.application_space.isDuplicate(unprotect_result.pn)) {
            conn.application_space.ack_needed = true;
            return;
        }

        // Record packet received
        conn.application_space.onPacketReceived(unprotect_result.pn);

        // Parse and process frames from decrypted payload
        const payload = decrypt_buf[unprotect_result.header_len .. unprotect_result.header_len + unprotect_result.payload_len];
        try processFrames(conn, payload);
    }

    /// Process all frames in a decrypted packet payload
    fn processFrames(conn: *connection.Connection, payload: []const u8) Error!void {
        var offset: usize = 0;

        while (offset < payload.len) {
            const result = frame.parseFrame(payload[offset..]) catch return Error.InvalidPacket;
            offset += result.consumed;

            switch (result.frame) {
                .padding => {}, // Ignore padding
                .ping => {}, // PING just triggers ACK
                .ack => |ack| {
                    conn.processAckFrame(ack, types.PacketNumberSpace.application);
                },
                .stream => |stream_frame| {
                    try processStreamFrame(conn, stream_frame);
                },
                .max_data => |max_data| {
                    conn.processMaxDataFrame(max_data.maximum_data);
                },
                .max_stream_data => |max_stream_data| {
                    if (conn.getStream(max_stream_data.stream_id)) |s| {
                        s.updateSendLimit(max_stream_data.maximum_stream_data);
                    }
                },
                .max_streams => |max_streams| {
                    // Update stream limits
                    if (conn.stream_manager) |*mgr| {
                        if (max_streams.bidirectional) {
                            mgr.max_streams_bidi_local = max_streams.maximum_streams;
                        } else {
                            mgr.max_streams_uni_local = max_streams.maximum_streams;
                        }
                    }
                },
                .connection_close => |close_frame| {
                    conn.processConnectionClose(close_frame.error_code, close_frame.reason_phrase);
                },
                .handshake_done => {
                    // Server confirms handshake complete
                    if (!conn.is_server) {
                        conn.onHandshakeComplete();
                    }
                },
                .reset_stream => |reset| {
                    if (conn.getStream(reset.stream_id)) |s| {
                        s.onReset(reset.final_size) catch |err| {
                            std.log.debug("QUIC stream reset failed: {}", .{err});
                        };
                    }
                },
                .stop_sending => |stop| {
                    if (conn.getStream(stop.stream_id)) |s| {
                        s.reset(stop.application_error_code);
                    }
                },
                .path_challenge => |challenge| {
                    // Queue PATH_RESPONSE with same data
                    conn.queuePathResponse(challenge.data);
                },
                .path_response => |response_frame| {
                    // Validate path response against pending challenge
                    conn.validatePathResponse(response_frame.data);
                },
                .new_connection_id => |new_cid| {
                    conn.addPeerConnectionId(new_cid);
                },
                .retire_connection_id => |retire| {
                    conn.retireConnectionId(retire.sequence_number);
                },
                else => {}, // Ignore other frame types for now
            }
        }
    }

    /// Process a STREAM frame
    fn processStreamFrame(conn: *connection.Connection, stream_frame: frame.StreamFrame) Error!void {
        // Get or create the stream
        const s = conn.getOrCreateStream(stream_frame.stream_id) catch |err| {
            return switch (err) {
                error.OutOfMemory => Error.OutOfMemory,
                error.StreamLimitExceeded => Error.ProtocolError,
                error.InvalidState, error.ConnectionClosed => Error.ProtocolError,
                else => Error.ProtocolError,
            };
        };

        // Snapshot recv_offset so we can credit connection-level flow
        // control for just the newly-in-order bytes this frame added.
        const recv_offset_before = s.recv_offset;

        // Deliver data to the Stream. This reassembles out-of-order
        // STREAM frames into `recv_buffer.items` and advances
        // `recv_offset` by the contiguous progress the frame enabled.
        s.receive(stream_frame.offset, stream_frame.data, stream_frame.fin) catch |err| switch (err) {
            stream.Error.FlowControlError => return Error.ProtocolError,
            stream.Error.FinalSizeError => return Error.ProtocolError,
            stream.Error.InvalidStreamState => return Error.ProtocolError,
            stream.Error.OutOfMemory => return Error.OutOfMemory,
            else => return Error.ProtocolError,
        };

        // Credit connection flow control by the in-order bytes that
        // actually landed (possibly zero for a pure out-of-order
        // frame). Zero progress with no FIN → nothing more to do; the
        // Stack will see the bytes once an earlier hole is filled.
        const new_bytes = s.recv_offset - recv_offset_before;
        if (new_bytes > 0) {
            conn.flow_control.onDataReceived(new_bytes) catch {
                return Error.ProtocolError;
            };
        }

        // Pull the in-order contiguous bytes from the Stream and hand
        // them to the HTTP/3 stack. Feeding reassembled in-order bytes
        // (instead of raw `stream_frame.data`) fixes findings #2 and
        // #3 in `docs/design/8.0-h3-performance-plan.md`: h3 frames
        // that span multiple QUIC STREAM frames are now correctly
        // reassembled, and out-of-order STREAM frames never feed the
        // h3 parser out of order.
        //
        // We intentionally do NOT call `s.consumeRead(result.consumed)`
        // here. The Stream's `recv_buffer.items` slice is what the
        // Stack just parsed; `RequestReadyEvent.body` (emitted by
        // defer-until-FIN `processRequestStream`) points directly into
        // those bytes. A full-consume path in `consumeRead` calls
        // `clearRetainingCapacity` which is safe (it leaves the
        // backing storage intact) — but a partial-consume path does a
        // `copyForwards` memmove that WOULD corrupt the body slice
        // before `Server.handleDatagram` gets to dispatch it. The
        // dispatch path calls `conn.clearH3RequestStream(stream_id)`
        // after running the handler; that's where the buffer is
        // reclaimed, not here.
        const contiguous = s.read();
        if (contiguous.len == 0 and !stream_frame.fin) return;

        const fin_now = s.recv_fin_offset != null and s.recv_offset >= s.recv_fin_offset.?;
        _ = conn.processHttp3Stream(stream_frame.stream_id, contiguous, fin_now) catch |err| {
            std.log.debug("HTTP/3 stream processing failed: stream={} err={}", .{ stream_frame.stream_id, err });
            return;
        };
    }

    /// Get pending HTTP/3 events from the connection
    fn getHttp3Events(conn: *connection.Connection) []http3.Event {
        if (conn.http3_stack) |*stack| {
            return stack.events.items;
        }
        return &.{};
    }

    /// Build whatever needs to go on the wire right now for `conn`. Called
    /// after every processPacket invocation. Coalesces an Initial, a
    /// Handshake, and a 1-RTT packet into a single UDP datagram (RFC 9000
    /// §12.2) — emitting only the levels that have something to say:
    ///
    ///   - Initial: pending CRYPTO bytes (server's ServerHello), or an ACK
    ///     for a received Initial. Skipped once the connection enters the
    ///     handshake phase and Initial keys are dropped.
    ///   - Handshake: pending CRYPTO bytes (server's EE+Cert+CertVerify+
    ///     Finished), or an ACK for a received Handshake.
    ///   - 1-RTT: HANDSHAKE_DONE (once on the first 1-RTT we send), an
    ///     ACK for a received 1-RTT, plus any pending HTTP/3 stream data.
    ///
    /// Returns an empty slice if there's nothing to send.
    fn buildResponseFlight(self: *Handler, conn: *connection.Connection) Error![]const u8 {
        var offset: usize = 0;

        // What will we end up emitting? We need to know in advance to
        // decide whether the Initial datagram-padding requirement still
        // applies (it only does until the handshake completes).
        const initial_keys_opt: ?crypto.Keys = conn.crypto_ctx.initial.server;
        const handshake_keys_opt: ?crypto.Keys = conn.crypto_ctx.handshake.server;
        const application_keys_opt: ?crypto.Keys = conn.crypto_ctx.application.server;

        const initial_crypto = if (initial_keys_opt != null) conn.getPendingCryptoData(types.PacketNumberSpace.initial) else &.{};
        const handshake_crypto = if (handshake_keys_opt != null) conn.getPendingCryptoData(types.PacketNumberSpace.handshake) else &.{};

        const want_initial = initial_keys_opt != null and (initial_crypto.len > 0 or conn.initial_space.ack_needed);
        const want_handshake = handshake_keys_opt != null and (handshake_crypto.len > 0 or conn.handshake_space.ack_needed);
        const want_one_rtt = application_keys_opt != null and conn.state == .connected and
            (conn.application_space.ack_needed or !conn.handshake_done_sent or
            conn.has1RttPayloadPending() or conn.needsMaxData() or
            conn.getStreamNeedingFlowControl() != null or conn.hasPendingPathResponse());

        // Pre-handshake datagrams must be padded to 1200 bytes (RFC 9000
        // §14.1). After handshake-complete this no longer applies.
        const need_pad_to_1200 = !conn.handshake_done_sent;

        // ---- Initial packet ----
        if (want_initial) {
            const built = try buildHandshakePacket(
                self.response_buffer[offset..],
                .{
                    .packet_type = .initial,
                    .conn = conn,
                    .crypto_data = initial_crypto,
                    .keys = &initial_keys_opt.?,
                    // Only request 1200-byte padding from the *last* long-
                    // header packet in the coalesced flight; otherwise inner
                    // packets blow past their length field.
                    .pad_datagram_to = if (need_pad_to_1200 and !want_handshake and !want_one_rtt) 1200 else 0,
                    .datagram_bytes_so_far = offset,
                    .ack_largest = if (conn.initial_space.ack_needed) conn.initial_space.largest_received else null,
                    .ack_first_range = conn.initial_space.firstAckRange(),
                },
            );
            offset += built.bytes_written;
            if (initial_crypto.len > 0) {
                conn.consumePendingCryptoData(types.PacketNumberSpace.initial, initial_crypto.len);
            }
            conn.initial_space.ack_needed = false;
        }

        // ---- Handshake packet ----
        if (want_handshake) {
            const built = try buildHandshakePacket(
                self.response_buffer[offset..],
                .{
                    .packet_type = .handshake,
                    .conn = conn,
                    .crypto_data = handshake_crypto,
                    .keys = &handshake_keys_opt.?,
                    .pad_datagram_to = if (need_pad_to_1200 and !want_one_rtt) 1200 else 0,
                    .datagram_bytes_so_far = offset,
                    .ack_largest = if (conn.handshake_space.ack_needed) conn.handshake_space.largest_received else null,
                    .ack_first_range = conn.handshake_space.firstAckRange(),
                },
            );
            offset += built.bytes_written;
            if (handshake_crypto.len > 0) {
                conn.consumePendingCryptoData(types.PacketNumberSpace.handshake, handshake_crypto.len);
            }
            conn.handshake_space.ack_needed = false;
        }

        // ---- 1-RTT packet ----
        if (want_one_rtt) {
            const built = try buildShortPacket(
                self.response_buffer[offset..],
                .{
                    .conn = conn,
                    .keys = &application_keys_opt.?,
                    .ack_largest = if (conn.application_space.ack_needed) conn.application_space.largest_received else null,
                    .ack_first_range = conn.application_space.firstAckRange(),
                    .send_handshake_done = !conn.handshake_done_sent,
                },
            );
            offset += built.bytes_written;
            conn.application_space.ack_needed = false;
            if (!conn.handshake_done_sent) conn.handshake_done_sent = true;
        }

        return self.response_buffer[0..offset];
    }

    /// Get count of active connections
    pub fn connectionCount(self: *const Handler) usize {
        return self.pool.count();
    }

    /// Clean up closed connections
    pub fn cleanup(self: *Handler) void {
        // Track how many connections we're closing
        var it = self.pool.iterator();
        while (it.next()) |conn| {
            if (!conn.isAlive() or conn.isIdleTimedOut()) {
                const is_error = conn.close_error != null and conn.close_error.? != .no_error;
                const is_timeout = conn.isIdleTimedOut();
                metrics_mw.getStore().recordQuicConnectionClose(is_error, is_timeout);
            }
        }
        self.pool.cleanup();
    }

    /// Record RTT sample from ACK processing
    pub fn recordRttSample(rtt_us: u64) void {
        metrics_mw.getStore().recordQuicRtt(rtt_us);
    }

    /// Record packet sent
    pub fn recordPacketSent() void {
        metrics_mw.getStore().recordQuicPackets(1, 0, 0);
    }

    /// Record packet lost
    pub fn recordPacketLost() void {
        metrics_mw.getStore().recordQuicPackets(0, 0, 1);
    }
};

/// Build a single QUIC long-header packet (Initial or Handshake) into `out`.
/// Lays down the header, an optional ACK frame, a CRYPTO frame carrying the
/// caller-supplied handshake bytes, optional PADDING to satisfy the RFC 9000
/// §14.1 1200-byte minimum on the *datagram*, then runs AEAD packet
/// protection + header protection over the result.
const BuildPacketOptions = struct {
    packet_type: types.PacketType,
    conn: *connection.Connection,
    crypto_data: []const u8,
    keys: *const crypto.Keys,
    /// If non-zero, pad so the total datagram (this packet + everything
    /// already in the buffer up to `datagram_bytes_so_far`) reaches at least
    /// this many bytes.
    pad_datagram_to: usize,
    datagram_bytes_so_far: usize,
    /// If non-null, emit an ACK frame acking the contiguous range
    /// [ack_largest - ack_first_range, ack_largest] in the matching number space.
    ack_largest: ?u64,
    ack_first_range: u64 = 0,
};

const BuildPacketResult = struct {
    bytes_written: usize,
};

fn buildHandshakePacket(out: []u8, opts: BuildPacketOptions) Error!BuildPacketResult {
    const conn_ref = opts.conn;

    // ---- Header ----
    var off: usize = 0;

    // First byte: long header (0x80) | fixed (0x40) | type (00=Initial, 10=Handshake)
    // | reserved 00 | PN length 00 (1 byte)
    const type_bits: u8 = switch (opts.packet_type) {
        .initial => 0x00,
        .handshake => 0x20,
        else => return Error.InvalidPacket,
    };
    if (off >= out.len) return Error.HandshakeFailed;
    out[off] = 0xc0 | type_bits;
    off += 1;

    // Version (QUIC v1)
    if (off + 4 > out.len) return Error.HandshakeFailed;
    out[off] = 0x00;
    out[off + 1] = 0x00;
    out[off + 2] = 0x00;
    out[off + 3] = 0x01;
    off += 4;

    // DCID length + DCID
    if (off + 1 + conn_ref.peer_cid.len > out.len) return Error.HandshakeFailed;
    out[off] = conn_ref.peer_cid.len;
    off += 1;
    if (conn_ref.peer_cid.len > 0) {
        @memcpy(out[off .. off + conn_ref.peer_cid.len], conn_ref.peer_cid.slice());
        off += conn_ref.peer_cid.len;
    }

    // SCID length + SCID
    if (off + 1 + conn_ref.our_cid.len > out.len) return Error.HandshakeFailed;
    out[off] = conn_ref.our_cid.len;
    off += 1;
    if (conn_ref.our_cid.len > 0) {
        @memcpy(out[off .. off + conn_ref.our_cid.len], conn_ref.our_cid.slice());
        off += conn_ref.our_cid.len;
    }

    // Token length (Initial only, always 0 for server-side response)
    if (opts.packet_type == .initial) {
        if (off >= out.len) return Error.HandshakeFailed;
        out[off] = 0x00;
        off += 1;
    }

    // Length field placeholder — encoded as a 2-byte varint (0x4000 | value).
    // We'll fill it in once we know the payload+tag size.
    if (off + 2 > out.len) return Error.HandshakeFailed;
    const length_offset = off;
    off += 2;

    // Packet number — 1 byte for now (sufficient for low PN values during handshake)
    const pn_offset = off;
    const pn_len: u8 = 1;
    const space_kind: types.PacketNumberSpace = switch (opts.packet_type) {
        .initial => .initial,
        .handshake => .handshake,
        else => return Error.InvalidPacket,
    };
    const space = conn_ref.getPacketSpace(space_kind);
    const pn = space.allocatePacketNumber();
    if (off >= out.len) return Error.HandshakeFailed;
    out[off] = @truncate(pn);
    off += 1;

    const header_len = off;

    // ---- Plaintext payload ----
    // Optional ACK frame. The first ACK range is computed from the
    // receive bitmap so we never lie about packets we haven't seen.
    if (opts.ack_largest) |largest| {
        const acked = frame.writeAckRange(out[off..], largest, opts.ack_first_range, 0) catch return Error.HandshakeFailed;
        off += acked;
    }

    // CRYPTO frame carrying the TLS handshake bytes (if any)
    if (opts.crypto_data.len > 0) {
        // CRYPTO offset is per-encryption-level, monotonically increasing.
        // For now we always emit at offset 0 because we drain the entire
        // queue in one go and only ever build one packet per level per
        // server flight. (Multi-packet handshake flights would need an
        // out-of-line offset cursor.)
        const written = frame.writeCrypto(out[off..], 0, opts.crypto_data) catch return Error.HandshakeFailed;
        off += written;
    }

    // PADDING to satisfy the datagram minimum (RFC 9000 §14.1)
    if (opts.pad_datagram_to > 0) {
        // Required total datagram size minus what's already in the buffer
        // before this packet. The current packet contributes `off` plain
        // bytes plus AEAD_TAG_LEN once protected.
        const target = opts.pad_datagram_to;
        const bytes_before = opts.datagram_bytes_so_far;
        const min_packet_size = if (target > bytes_before) target - bytes_before else 0;
        // Account for the AEAD tag that protectPacket will append.
        while (off + crypto.AEAD_TAG_LEN < min_packet_size) {
            if (off >= out.len) return Error.HandshakeFailed;
            out[off] = 0x00; // PADDING frame (frame type 0x00)
            off += 1;
        }
    }

    // ---- Length field fixup ----
    const payload_len = off - header_len;
    const length_value: u64 = pn_len + payload_len + crypto.AEAD_TAG_LEN;
    // 2-byte varint: 0x40 | high6 || low8
    if (length_value > 0x3fff) return Error.HandshakeFailed;
    out[length_offset] = @intCast(0x40 | ((length_value >> 8) & 0x3f));
    out[length_offset + 1] = @intCast(length_value & 0xff);

    // ---- AEAD packet protection + header protection ----
    const protected_len = crypto.protectPacket(
        opts.keys,
        pn,
        header_len,
        pn_offset,
        pn_len,
        out,
        off,
    ) catch return Error.HandshakeFailed;

    return .{ .bytes_written = protected_len };
}

/// Options for building a short-header (1-RTT) packet.
///
/// Exposed so the Server's response path can call `buildShortPacket`
/// directly instead of maintaining its own parallel 1-RTT builder
/// (`server.zig::buildStreamPacket` pre-PR-PERF-0). Unifying on a
/// single builder is the prerequisite for GSO batching in PR PERF-1:
/// every 1-RTT packet needs the same layout so a run of them can be
/// handed to `UDP_SEGMENT` in one sendmsg.
pub const BuildShortPacketOptions = struct {
    conn: *connection.Connection,
    keys: *const crypto.Keys,
    /// If non-null, emit an ACK frame acking the contiguous range
    /// [ack_largest - ack_first_range, ack_largest] in the app space.
    ack_largest: ?u64 = null,
    ack_first_range: u64 = 0,
    /// Should this packet include a HANDSHAKE_DONE frame?
    send_handshake_done: bool = false,
    /// Optional STREAM frame payload to include. When set the builder
    /// writes a STREAM frame with the given stream_id / data / fin
    /// after any ACK / HANDSHAKE_DONE / pending-uni-stream frames,
    /// before padding-for-HP-sample and encryption. Used by the h3
    /// response path to emit each 1200-byte response chunk through
    /// the unified builder.
    stream_data: ?StreamFramePayload = null,
};

pub const StreamFramePayload = struct {
    stream_id: u64,
    offset: u64 = 0,
    data: []const u8,
    fin: bool,
};

/// Build a single 1-RTT (short header) QUIC packet into `out`. Layout is
/// much simpler than long-header: just flags byte + DCID + packet number,
/// then frames, then AEAD + header protection.
pub fn buildShortPacket(out: []u8, opts: BuildShortPacketOptions) Error!BuildPacketResult {
    const conn_ref = opts.conn;
    var off: usize = 0;

    // Short header first byte (RFC 9000 §17.3.1):
    //   0|1|S|R|R|K|P|P
    //   ^   ^   ^   ^----- packet number length (00 = 1 byte)
    //   |   |   key phase (0)
    //   |   spin bit (0)
    //   fixed bit (1)
    // High bit (form) = 0 = short header.
    if (off >= out.len) return Error.HandshakeFailed;
    out[off] = 0x40; // 0b01000000 — fixed bit set, all other flags 0
    off += 1;

    // DCID: peer's connection ID (no length byte in short header form;
    // both endpoints know each other's CID lengths from the handshake).
    if (off + conn_ref.peer_cid.len > out.len) return Error.HandshakeFailed;
    if (conn_ref.peer_cid.len > 0) {
        @memcpy(out[off .. off + conn_ref.peer_cid.len], conn_ref.peer_cid.slice());
        off += conn_ref.peer_cid.len;
    }

    // Packet number — 1 byte for now, like the long-header builder.
    const pn_offset = off;
    const pn_len: u8 = 1;
    const pn = conn_ref.application_space.allocatePacketNumber();
    if (off >= out.len) return Error.HandshakeFailed;
    out[off] = @truncate(pn);
    off += 1;

    const header_len = off;

    // ---- Plaintext payload ----

    // ACK frame (per-application-space). First ACK range from the
    // receive bitmap so we never claim packets we haven't actually seen.
    if (opts.ack_largest) |largest| {
        const acked = frame.writeAckRange(out[off..], largest, opts.ack_first_range, 0) catch return Error.HandshakeFailed;
        off += acked;
    }

    // HANDSHAKE_DONE frame (sent exactly once after handshake completes)
    if (opts.send_handshake_done) {
        const written = frame.writeHandshakeDone(out[off..]) catch return Error.HandshakeFailed;
        off += written;
    }

    // Drain pending bytes from the server's three required uni streams
    // (control / QPACK encoder / QPACK decoder). The control stream
    // carries the SETTINGS frame; the QPACK streams carry just their
    // type byte (until we add dynamic-table support). The h3 client
    // (curl/ngtcp2) waits for all three streams to be opened before
    // accepting response data on request streams.
    while (conn_ref.nextPendingUniStream()) |uni| {
        const written = frame.writeStream(out[off..], uni.stream_id, 0, uni.data, false) catch return Error.HandshakeFailed;
        off += written;
        conn_ref.clearPendingUniStream(uni.stream_id);
    }

    // ---- Transport control frames (RFC 9000 §19) ----
    //
    // These are computed lazily by Connection when flow-control
    // thresholds are crossed or PATH_CHALLENGE is received, but they
    // were never emitted on the wire until now.

    // MAX_DATA: grow the connection-level receive window.
    if (conn_ref.needsMaxData()) {
        const written = conn_ref.buildMaxDataFrame(out[off..]) catch 0;
        off += written;
    }

    // MAX_STREAM_DATA: grow per-stream receive windows.
    // Emit up to 4 per packet to limit frame bloat.
    {
        var max_sd_count: usize = 0;
        while (max_sd_count < 4) : (max_sd_count += 1) {
            const sid = conn_ref.getStreamNeedingFlowControl() orelse break;
            const written = conn_ref.buildMaxStreamDataFrame(out[off..], sid) catch break;
            off += written;
        }
    }

    // PATH_RESPONSE: reply to a received PATH_CHALLENGE.
    if (conn_ref.takePendingPathResponse()) |path_data| {
        const written = frame.writePathResponse(out[off..], path_data) catch 0;
        off += written;
    }

    // Optional response STREAM frame for the h3 data path. The Server
    // passes one of these per response chunk via `opts.stream_data`;
    // pre-PR-PERF-0 each chunk went through a separate
    // `server.zig::buildStreamPacket` builder that bypassed the ACK /
    // HANDSHAKE_DONE / uni-stream path entirely. Now every 1-RTT
    // packet is built through this single function.
    if (opts.stream_data) |sd| {
        if (off + sd.data.len + 16 > out.len) return Error.HandshakeFailed;
        const written = frame.writeStream(out[off..], sd.stream_id, sd.offset, sd.data, sd.fin) catch return Error.HandshakeFailed;
        off += written;
    }

    // Need at least one byte of plaintext (a PING frame, type 0x01) so
    // header protection has a sample to work on. RFC 9001 §5.4.2: the
    // packet must have at least 4 bytes of payload after the packet
    // number for the HP sample.
    while (off - header_len < 4) {
        if (off >= out.len) return Error.HandshakeFailed;
        out[off] = 0x00; // PADDING
        off += 1;
    }

    // ---- AEAD + header protection ----
    const protected_len = crypto.protectPacket(
        opts.keys,
        pn,
        header_len,
        pn_offset,
        pn_len,
        out,
        off,
    ) catch return Error.HandshakeFailed;

    return .{ .bytes_written = protected_len };
}

// Tests
test "handler initialization" {
    if (!build_options.enable_http3) return;
    const allocator = std.testing.allocator;
    var handler = Handler.init(allocator, true, 100);
    defer handler.deinit();

    try std.testing.expectEqual(@as(usize, 0), handler.connectionCount());
}

test "handler processes Initial packet" {
    if (!build_options.enable_http3) return;
    const allocator = std.testing.allocator;
    var server_handler = Handler.init(allocator, true, 100);
    defer server_handler.deinit();

    const dcid_bytes = [_]u8{0xaa} ** 8;
    const scid_bytes = [_]u8{0xbb} ** 4;
    var pkt_buf: [types.Constants.min_initial_packet_size]u8 = undefined;
    const packet_bytes = try test_utils.buildClientInitialPacket(&pkt_buf, &dcid_bytes, &scid_bytes, 256);

    var peer_addr: connection_pool.SockAddrStorage = undefined;
    @memset(std.mem.asBytes(&peer_addr), 0);

    const result = try server_handler.processPacket(packet_bytes, peer_addr);
    try std.testing.expect(result.new_connection);
    try std.testing.expect(result.conn != null);
    try std.testing.expect(result.response != null);
    try std.testing.expectEqual(@as(usize, 1), server_handler.connectionCount());
}
